# Generated by pnpm --filter @latticeag/events codegen. Do not edit.
"""Pydantic models and parse_envelope for latticeag-events."""

from __future__ import annotations

import json
from typing import Any

from latticeag_events.models import *

EVENT_NAMES = frozenset({
    "belief_extracted",
    "policy_decision",
    "verdict",
    "approval_granted",
    "compensation_executed",
    "receipt_issued",
    "session_recorded",
    "diff_computed",
    "tool_observed",
    "extension",
    "bus_overflow",
    "adapter_error",
})

MAX_ENVELOPE_BYTES = 262144


class EnvelopeTooLargeError(Exception):
    def __init__(self, nbytes: int) -> None:
        super().__init__(f"JSON.stringify(envelope) exceeds {MAX_ENVELOPE_BYTES} bytes: {nbytes}")
        self.bytes = nbytes


class EventPayloadError(Exception):
    def __init__(self, message: str, pointer: str) -> None:
        super().__init__(message)
        self.pointer = pointer


def parse_envelope(data: dict) -> Any:
    if not isinstance(data, dict):
        raise TypeError("parse_envelope expects a dict")
    encoded = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
    if len(encoded) > MAX_ENVELOPE_BYTES:
        raise EnvelopeTooLargeError(len(encoded))
    return data
