# Generated by pnpm --filter @latticeag/events codegen. Do not edit.

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Literal, Optional, Union

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Product(StrEnum):
    polybrain = 'polybrain'
    polygnosis = 'polygnosis'
    polyflow = 'polyflow'
    polyscribe = 'polyscribe'
    polymesh = 'polymesh'
    lexgateway = 'lexgateway'
    lexrouter = 'lexrouter'
    lexrapid = 'lexrapid'
    lexshield = 'lexshield'
    lexverdict = 'lexverdict'
    vektor = 'vektor'
    vekdata = 'vekdata'
    vekinbox = 'vekinbox'
    axicontext = 'axicontext'
    axion = 'axion'
    visboard = 'visboard'
    viscompile = 'viscompile'
    visreplay = 'visreplay'
    forgedistill = 'forgedistill'
    latticeag = 'latticeag'


class Producer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product: Product
    adapter: constr(min_length=1)
    adapter_version: constr(min_length=1)


class Redaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applied: bool
    keys: list[str]
    pattern_hits: conint(ge=0)


class Type(StrEnum):
    causal = 'causal'
    assumption = 'assumption'
    intention = 'intention'
    evidence = 'evidence'
    uncertainty = 'uncertainty'
    contradiction = 'contradiction'
    planning = 'planning'
    self_correction = 'self-correction'


class Belief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    type: Type
    text: str
    evidence: str | None = None
    confidence: confloat(ge=0.0, le=1.0)
    action_taken: str | None = None
    line: int
    axion_timestamp_ms: float


class Provider(StrEnum):
    openai = 'openai'
    anthropic = 'anthropic'


class Batch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spec: Literal['axion.belief_batch.v1']
    calls_in_session: int
    provider: Provider | None = None
    model_name: str | None = None
    inbound_message_count: int | None = None
    redactions: int


class Source(StrEnum):
    tool_calls = 'tool_calls'
    tool_use = 'tool_use'


class ArgumentFingerprintSource(StrEnum):
    canonical = 'canonical'
    raw = 'raw'


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    name: constr(min_length=1)
    provider: Provider
    source: Source
    argument_fingerprint: str
    argument_fingerprint_source: ArgumentFingerprintSource
    argument_bytes: int
    source_class: Literal['tool_observed']


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    belief: Belief
    batch: Batch
    action: Action | None = None


class LatticeEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Literal['latticeag.events/1.0'] = Field(..., alias='$schema')
    schema_version: Literal[1]
    id: constr(pattern=r'^[0-7][0-9A-HJKMNP-TV-Z]{25}$')
    seq: conint(ge=1, le=9007199254740991)
    ts: AwareDatetime
    run_id: constr(min_length=1)
    session_id: constr(min_length=1)
    producer: Producer
    causation_id: constr(min_length=1) | None = None
    correlation_id: constr(min_length=1)
    redaction: Redaction
    name: Literal['belief_extracted']
    payload: Payload


class Decision(StrEnum):
    ALLOW = 'ALLOW'
    BLOCK = 'BLOCK'
    CHALLENGE = 'CHALLENGE'
    DEFER = 'DEFER'


class Tool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    namespace: str | None = None
    version: str | None = None


class Alternative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: str
    confidence: confloat(ge=0.0, le=1.0)


class Classification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: str
    confidence: confloat(ge=0.0, le=1.0)
    classifier: str
    alternatives: list[Alternative]


class Payload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: constr(min_length=1)
    decision: Decision
    matched_rule_id: str | None = None
    reason: str
    policy_version: str | None = None
    duration_ms: int
    challenge_id: str | None = None
    tool: Tool
    classifications: list[Classification]


class Verdict(StrEnum):
    pass_ = 'pass'
    steer = 'steer'


class Priority(StrEnum):
    low = 'low'
    normal = 'normal'
    high = 'high'
    critical = 'critical'


class Payload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: constr(min_length=1)
    key: constr(min_length=1)
    title: str
    workspace_id: constr(min_length=1)
    agent_id: constr(min_length=1)
    status: Literal['approved']
    action: str
    resolved_by: str | None = None
    resolved_at: str
    note: str | None = None
    priority: Priority


class StateTo(StrEnum):
    failed_verified = 'failed_verified'
    invalidated = 'invalidated'
    executed = 'executed'


class Source1(StrEnum):
    metadata = 'metadata'
    fixture = 'fixture'


class Payload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: constr(min_length=1)
    execution_id: constr(min_length=1)
    state_from: Literal['compensation_required']
    state_to: StateTo
    action: str
    note: str | None = None
    source: Source1 | None = None


class Tier(StrEnum):
    agent_asserted = 'agent_asserted'
    gateway_verified = 'gateway_verified'
    downstream_attested = 'downstream_attested'


class EventCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: int
    reasoning: int
    tool_call: int
    tool_result: int
    output: int
    error: int


class Payload6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visreplay_schema: Literal['visreplay/session/1.0']
    visreplay_session_id: constr(min_length=1)
    session_name: str
    agent_type: str
    started_at: str
    ended_at: str | None = None
    path: constr(min_length=1)
    event_count: int
    event_counts: EventCounts


class ViscompileSchemaVersion(Enum):
    number_1 = 1
    number_2 = 2


class Summary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unchanged: int
    added: int
    removed: int
    changed: int
    regressions: int
    improvements: int


class Status(StrEnum):
    unchanged = 'unchanged'
    added = 'added'
    removed = 'removed'
    changed = 'changed'
    improved = 'improved'


class WhyCode(StrEnum):
    case_added = 'case_added'
    case_removed = 'case_removed'
    error_raised = 'error_raised'
    error_resolved = 'error_resolved'
    input_changed = 'input_changed'
    tool_call_reordered = 'tool_call_reordered'
    tool_call_removed = 'tool_call_removed'
    tool_call_added = 'tool_call_added'
    tool_call_arguments_changed = 'tool_call_arguments_changed'
    output_changed = 'output_changed'
    error_changed = 'error_changed'


class Case(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    status: Status
    regression: bool
    why_codes: list[WhyCode]


class LatticeExit(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2


class Payload7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['latticeag.viscompile.diff']
    viscompile_schema_version: ViscompileSchemaVersion
    beliefs_omitted: bool
    baseline_path: constr(min_length=1)
    target_path: constr(min_length=1)
    report_path: constr(min_length=1)
    summary: Summary
    cases: list[Case]
    lattice_exit: LatticeExit


class Source2(StrEnum):
    axion = 'axion'
    visreplay = 'visreplay'


class Reason(StrEnum):
    capacity = 'capacity'
    rotate = 'rotate'
    sync_outbox = 'sync_outbox'


class Payload10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Reason
    dropped_id: str | None = None
    dropped_name: str | None = None
    ring_size: int
    ring_capacity: int


class Payload11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter: constr(min_length=1)
    message: str
    cause_name: str | None = None
    event_id: str | None = None


class FieldSchema(RootModel[Literal['latticeag.events/1.0']]):
    root: Literal['latticeag.events/1.0']


class CausationId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class CorrelationId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Id(RootModel[constr(pattern=r'^[0-7][0-9A-HJKMNP-TV-Z]{25}$')]):
    root: constr(pattern=r'^[0-7][0-9A-HJKMNP-TV-Z]{25}$')


class ProducerModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product: Product
    adapter: constr(min_length=1)
    adapter_version: constr(min_length=1)


class RunId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class SchemaVersion(RootModel[Literal[1]]):
    root: Literal[1]


class Seq(RootModel[conint(ge=1, le=9007199254740991)]):
    root: conint(ge=1, le=9007199254740991)


class SessionId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Ts(RootModel[AwareDatetime]):
    root: AwareDatetime


class ToolCall(RootModel[constr(max_length=8000)]):
    root: constr(max_length=8000)


class ToolCallSha256(RootModel[constr(pattern=r'^[0-9a-f]{64}$')]):
    root: constr(pattern=r'^[0-9a-f]{64}$')


class SourceModel(StrEnum):
    metadata = 'metadata'
    fixture = 'fixture'


class LatticeEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['policy_decision']
    payload: Payload1


class Payload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verdict: Verdict
    confidence: confloat(ge=0.0, le=1.0)
    message: str | None
    tool_call: constr(max_length=8000)
    goal: ToolCall
    result: ToolCall
    tool_call_sha256: constr(pattern=r'^[0-9a-f]{64}$')
    goal_sha256: ToolCallSha256
    result_sha256: ToolCallSha256
    latency_ms: int


class LatticeEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['verdict']
    payload: Payload2


class LatticeEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['approval_granted']
    payload: Payload3


class LatticeEvent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['compensation_executed']
    payload: Payload4


class Payload5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: constr(min_length=1)
    execution_id: constr(min_length=1)
    tier: Tier
    action: str
    issued_at: str
    payload_sha256: ToolCallSha256
    source: SourceModel | None = None


class LatticeEvent6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['receipt_issued']
    payload: Payload5


class LatticeEvent7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['session_recorded']
    payload: Payload6


class LatticeEvent8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['diff_computed']
    payload: Payload7


class LatticeEvent11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['bus_overflow']
    payload: Payload10


class LatticeEvent12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['adapter_error']
    payload: Payload11


class Payload8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Source2
    name: constr(min_length=1)
    arguments: dict[str, str | float | bool | Arguments | list[AdditionalProperties | None] | None]
    result: AdditionalProperties | None = None
    error: str | None = None
    argument_fingerprint: str | None = None
    visreplay_event_id: str | None = None
    axion_action_id: str | None = None


class LatticeEvent9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['tool_observed']
    payload: Payload8


class Payload9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extension_name: constr(pattern=r'^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$')
    payload: AdditionalProperties | None


class LatticeEvent10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: FieldSchema = Field(..., alias='$schema')
    schema_version: SchemaVersion
    id: Id
    seq: Seq
    ts: Ts
    run_id: RunId
    session_id: SessionId
    producer: ProducerModel
    causation_id: CausationId | None = None
    correlation_id: CorrelationId
    redaction: Redaction
    name: Literal['extension']
    payload: Payload9


class LatticeEvent(
    RootModel[
        LatticeEvent1
        | LatticeEvent2
        | LatticeEvent3
        | LatticeEvent4
        | LatticeEvent5
        | LatticeEvent6
        | LatticeEvent7
        | LatticeEvent8
        | LatticeEvent9
        | LatticeEvent10
        | LatticeEvent11
        | LatticeEvent12
    ]
):
    root: LatticeEvent1 | LatticeEvent2 | LatticeEvent3 | LatticeEvent4 | LatticeEvent5 | LatticeEvent6 | LatticeEvent7 | LatticeEvent8 | LatticeEvent9 | LatticeEvent10 | LatticeEvent11 | LatticeEvent12


class Model(RootModel[LatticeEvent]):
    root: LatticeEvent


class Arguments(
    RootModel[dict[str, Union[str | float | bool | None, "Arguments", list[Optional["AdditionalProperties"]]]]]
):
    root: dict[str, Union[str | float | bool | None, "Arguments", list[Optional["AdditionalProperties"]]]]


class AdditionalProperties(
    RootModel[Union[str | float | bool | None, Arguments, list[Optional["AdditionalProperties"]]]]
):
    root: Union[str | float | bool | None, Arguments, list[Optional["AdditionalProperties"]]]


Payload8.model_rebuild()
Payload9.model_rebuild()
Arguments.model_rebuild()
