# Generated by latticeag / @latticeag/core attach langgraph. Safe to delete.
import json
import os
import urllib.request

INGEST = os.environ["LATTICEAG_INGEST_URL"] + "/generic"


def on_tool_end(name: str, arguments: dict, result) -> None:
    body = json.dumps({
        "name": "tool_observed",
        "payload": {
            "source": "visreplay",
            "name": name,
            "arguments": arguments,
            "result": result,
        },
    }).encode("utf-8")
    req = urllib.request.Request(
        INGEST,
        data=body,
        headers={"content-type": "application/json"},
    )
    urllib.request.urlopen(req, timeout=2)
