import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import type { ZodType } from "zod";
import { EVENT_NAMES, type EventName } from "./types.js";
import {
  adapterErrorPayloadSchema,
  approvalGrantedPayloadSchema,
  beliefExtractedPayloadSchema,
  busOverflowPayloadSchema,
  compensationExecutedPayloadSchema,
  diffComputedPayloadSchema,
  extensionPayloadSchema,
  latticeEventSchema,
  policyDecisionPayloadSchema,
  receiptIssuedPayloadSchema,
  sessionRecordedPayloadSchema,
  toolObservedPayloadSchema,
  verdictPayloadSchema,
} from "./zod.js";

const DRAFT_2020_12 = "https://json-schema.org/draft/2020-12/schema";
const GENERATED_HEADER =
  "# Generated by pnpm --filter @latticeag/events codegen. Do not edit.";

const srcDir = path.dirname(fileURLToPath(import.meta.url));
export const pkgRoot = path.resolve(srcDir, "..");
const repoRoot = path.resolve(pkgRoot, "../..");

const payloadSchemas: Record<EventName, ZodType> = {
  belief_extracted: beliefExtractedPayloadSchema,
  policy_decision: policyDecisionPayloadSchema,
  verdict: verdictPayloadSchema,
  approval_granted: approvalGrantedPayloadSchema,
  compensation_executed: compensationExecutedPayloadSchema,
  receipt_issued: receiptIssuedPayloadSchema,
  session_recorded: sessionRecordedPayloadSchema,
  diff_computed: diffComputedPayloadSchema,
  tool_observed: toolObservedPayloadSchema,
  extension: extensionPayloadSchema,
  bus_overflow: busOverflowPayloadSchema,
  adapter_error: adapterErrorPayloadSchema,
};

export const GENERATED_PATHS = [
  "schemas/envelope.schema.json",
  ...EVENT_NAMES.map((name) => `schemas/payload-${name}.schema.json`),
  "schemas/codegen-lock.json",
  "python/latticeag_events/models.py",
  "python/latticeag_events/__init__.py",
  "VERSIONING.md",
] as const;

export function computeSourceHash(): string {
  const types = readFileSync(path.join(srcDir, "types.ts"));
  const zod = readFileSync(path.join(srcDir, "zod.ts"));
  return createHash("sha256").update(types).update("\0").update(zod).digest("hex");
}

function hashArtifacts(files: Record<string, string>): string {
  const h = createHash("sha256");
  for (const rel of Object.keys(files).sort()) {
    if (rel === "schemas/codegen-lock.json") {
      continue;
    }
    h.update(rel);
    h.update("\0");
    h.update(files[rel] ?? "");
    h.update("\0");
  }
  return h.digest("hex");
}

function toJsonSchemaDocument(schema: ZodType, name: string): string {
  const generated = zodToJsonSchema(schema, {
    name,
    $refStrategy: "root",
    target: "jsonSchema7",
  }) as Record<string, unknown>;
  generated.$schema = DRAFT_2020_12;
  return `${JSON.stringify(generated, null, 2)}\n`;
}

function payloadTitle(name: EventName): string {
  return `Payload_${name}`;
}

export function generateJsonSchemas(): Record<string, string> {
  const out: Record<string, string> = {
    "schemas/envelope.schema.json": toJsonSchemaDocument(
      latticeEventSchema,
      "LatticeEvent",
    ),
  };
  for (const name of EVENT_NAMES) {
    out[`schemas/payload-${name}.schema.json`] = toJsonSchemaDocument(
      payloadSchemas[name],
      payloadTitle(name),
    );
  }
  return out;
}

export function generateVersioningMarkdown(): string {
  return `# Versioning

Envelope \`schema_version\` is 1.

TypeScript uses a closed union of first-class event names plus \`extension\`.
Runtime parse stays open: an unknown \`name\` becomes \`UnknownLatticeEvent\`.
\`latticeag events --strict-names\` exits 1 on unknown names.

First-class names have no dots. Extension names use \`product.event\`, for example \`axion.loop_detected\`.

Adding a first-class name is a MINOR release. The PR must update \`EVENT_NAMES\`, \`PayloadMap\`, Zod, JSON Schema, then run:

\`\`\`
pnpm --filter @latticeag/events codegen
\`\`\`

Removing a field, renaming a field, or changing a field type is a MAJOR release and requires a new \`schema_version\`.

\`codegen.test.ts\` hashes \`types.ts\` and \`zod.ts\` against \`schemas/\` and \`python/\`. Drift fails CI.
`;
}

export function generatePythonInit(): string {
  const names = EVENT_NAMES.map((n) => `    "${n}",`).join("\n");
  return `${GENERATED_HEADER}
"""Pydantic models and parse_envelope for latticeag-events."""

from __future__ import annotations

import json
from typing import Any

from latticeag_events.models import *

EVENT_NAMES = frozenset({
${names}
})

MAX_ENVELOPE_BYTES = 262144


class EnvelopeTooLargeError(Exception):
    def __init__(self, nbytes: int) -> None:
        super().__init__(f"JSON.stringify(envelope) exceeds {MAX_ENVELOPE_BYTES} bytes: {nbytes}")
        self.bytes = nbytes


class EventPayloadError(Exception):
    def __init__(self, message: str, pointer: str) -> None:
        super().__init__(message)
        self.pointer = pointer


def parse_envelope(data: dict) -> Any:
    if not isinstance(data, dict):
        raise TypeError("parse_envelope expects a dict")
    encoded = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
    if len(encoded) > MAX_ENVELOPE_BYTES:
        raise EnvelopeTooLargeError(len(encoded))
    return data
`;
}

function runDatamodelCodegen(envelopeSchemaJson: string): string {
  const bin = path.join(repoRoot, ".venv", "bin", "datamodel-codegen");
  if (!existsSync(bin)) {
    throw new Error(
      `datamodel-codegen not found at ${bin}. Create the venv: python3 -m venv ${path.join(repoRoot, ".venv")} && ${path.join(repoRoot, ".venv", "bin", "pip")} install 'datamodel-code-generator>=0.26' 'pydantic>=2.10,<3' pytest hatchling`,
    );
  }
  const tmp = mkdtempSync(path.join(tmpdir(), "latticeag-events-"));
  try {
    const inputPath = path.join(tmp, "envelope.schema.json");
    const outputPath = path.join(tmp, "models.py");
    writeFileSync(inputPath, envelopeSchemaJson);
    execFileSync(
      bin,
      [
        "--input",
        inputPath,
        "--input-file-type",
        "jsonschema",
        "--output",
        outputPath,
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.11",
        "--use-standard-collections",
        "--use-union-operator",
        "--disable-timestamp",
        "--formatters",
        "builtin",
        "--custom-file-header",
        GENERATED_HEADER,
        "--custom-file-header-mode",
        "replace",
      ],
      { cwd: repoRoot, stdio: ["ignore", "pipe", "pipe"] },
    );
    let models = readFileSync(outputPath, "utf8");
    if (!models.startsWith(GENERATED_HEADER)) {
      models = `${GENERATED_HEADER}\n${models}`;
    }
    if (!models.endsWith("\n")) {
      models += "\n";
    }
    return models;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

export function generateArtifactMap(): Record<string, string> {
  const artifacts = generateJsonSchemas();
  artifacts["python/latticeag_events/models.py"] = runDatamodelCodegen(
    artifacts["schemas/envelope.schema.json"] ?? "",
  );
  artifacts["python/latticeag_events/__init__.py"] = generatePythonInit();
  artifacts["VERSIONING.md"] = generateVersioningMarkdown();
  const lock = {
    source: computeSourceHash(),
    artifacts: hashArtifacts(artifacts),
  };
  artifacts["schemas/codegen-lock.json"] = `${JSON.stringify(lock, null, 2)}\n`;
  return artifacts;
}

export function writeArtifacts(artifacts: Record<string, string>): void {
  for (const [rel, contents] of Object.entries(artifacts)) {
    const abs = path.join(pkgRoot, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, contents);
  }
}

export function checkArtifacts(artifacts: Record<string, string>): string[] {
  const drift: string[] = [];
  for (const [rel, contents] of Object.entries(artifacts)) {
    const abs = path.join(pkgRoot, rel);
    if (!existsSync(abs)) {
      drift.push(`missing ${rel}`);
      continue;
    }
    const onDisk = readFileSync(abs, "utf8");
    if (onDisk !== contents) {
      drift.push(`drift ${rel}`);
    }
  }
  return drift;
}

function isDirectRun(): boolean {
  const entry = process.argv[1];
  if (!entry) {
    return false;
  }
  const resolved = path.resolve(entry);
  return (
    import.meta.url === pathToFileURL(resolved).href ||
    resolved.endsWith(`${path.sep}codegen.ts`) ||
    resolved.endsWith(`${path.sep}codegen.js`)
  );
}

function main(): void {
  const check = process.argv.includes("--check");
  const artifacts = generateArtifactMap();
  if (check) {
    const drift = checkArtifacts(artifacts);
    if (drift.length > 0) {
      console.error(drift.join("\n"));
      process.exit(1);
    }
    return;
  }
  writeArtifacts(artifacts);
}

if (isDirectRun()) {
  main();
}
