import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { AgentAttachKit } from "./types.js";
import { injectAxionBaseUrls } from "./types.js";

export const LANGGRAPH_CALLBACK_PY = `# Generated by latticeag run --attach langgraph. Safe to delete.
import json, os, urllib.request

INGEST = os.environ["LATTICEAG_INGEST_URL"] + "/generic"

def on_tool_end(name: str, arguments: dict, result) -> None:
    body = json.dumps({
        "name": "tool_observed",
        "payload": {
            "source": "visreplay",
            "name": name,
            "arguments": arguments,
            "result": result,
        },
    }).encode("utf-8")
    req = urllib.request.Request(INGEST, data=body, headers={"content-type": "application/json"})
    urllib.request.urlopen(req, timeout=2)
`;

export const langgraphKit: AgentAttachKit = {
  id: "langgraph",
  detect(env, argv) {
    if (typeof env.LANGGRAPH === "string" && env.LANGGRAPH.length > 0) {
      return true;
    }
    return argv.some((token) => /langgraph/i.test(token));
  },
  injectEnv(env, ctx) {
    return injectAxionBaseUrls(env, ctx);
  },
  async beforeSpawn(cwd) {
    const dir = path.join(cwd, ".latticeag", "hooks");
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, "langgraph_callback.py"), LANGGRAPH_CALLBACK_PY);
  },
};
