import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { AgentAttachKit } from "./types.js";
import { injectAxionBaseUrls } from "./types.js";

export const OPENAI_AGENTS_HOOK = `// Generated by latticeag run --attach openai-agents. Safe to delete.
// latticeag does not patch node_modules.
//
// Wire Axion (or your OPENAI_BASE_URL) through the OpenAI Agents SDK:
//
//   import { setDefaultOpenAIClient } from "@openai/agents";
//   import { OpenAI } from "openai";
//
//   const client = new OpenAI({
//     baseURL: process.env.OPENAI_BASE_URL,
//     apiKey: process.env.OPENAI_API_KEY,
//   });
//   setDefaultOpenAIClient(client);
//
// Then import this file from your agent entry, or copy the snippet above.
`;

export const openaiAgentsKit: AgentAttachKit = {
  id: "openai-agents",
  detect(env, argv) {
    if (typeof env.OPENAI_AGENTS === "string" && env.OPENAI_AGENTS.length > 0) {
      return true;
    }
    return argv.some((token) => /openai-agents|@openai\/agents/i.test(token));
  },
  injectEnv(env, ctx) {
    return injectAxionBaseUrls(env, ctx);
  },
  async beforeSpawn(cwd) {
    const dir = path.join(cwd, ".latticeag");
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, "openai-agents-hook.mjs"), OPENAI_AGENTS_HOOK);
  },
};
